version: build-{build}-{branch}

environment:
  matrix:
    # https://www.appveyor.com/docs/installed-software#python lists available
    # versions
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python310"
    - PYTHON: "C:\\Python311"

init:
  - "echo %PYTHON%"

install:
  - ps: |
      if (-not (Test-Path $env:PYTHON)) {
        curl -o install_python.ps1 https://raw.githubusercontent.com/matthew-brett/multibuild/11a389d78892cf90addac8f69433d5e22bfa422a/install_python.ps1
        .\install_python.ps1
      }
  - ps: if (-not (Test-Path $env:PYTHON)) { throw "No $env:PYTHON" }
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install -U virtualenv  # upgrade pip in tox's virtualenvs
  - pip install tox
  - choco install graphviz --version=2.38.0.20190211
  - dot -V

build: off

test_script:
  - tox -e py
